/**
 * Style Dictionary pipeline for the Composa UI design system.
 *
 * Single JSON source  ->  multiple platforms:
 *   tokens/primitive/*.json  (figma.composa.* raw values, light + dark)
 *   tokens/semantic/*.json   (composa.* aliases referencing primitives)
 *        |
 *        +--> design/generated/composa-core-tokens.css   (--figma-composa-* primitives, :root + dark)
 *        +--> design/generated/composa-core-tokens.json   (source metadata + aliases mirror)
 *        +--> design/generated/composa-semantic-tokens.css (--composa-* alias references; package/parity artifact)
 *        +--> design/generated/tokens.js                  (nested ES-module token object — web JS consumption)
 *        +--> design/generated/Tokens.swift               (enum/struct stub — multi-platform showcase)
 *
 * The runtime CSS contract stays in the hand-authored design/tokens.css, which
 * @imports the generated primitive CSS and keeps every --composa-* alias plus the
 * hand-authored component/overrides tokens (control/menu/switch/tooltip/dialog/
 * tabs/radicle, and computed values like radius-large / text-secondary-observed
 * that do not reference a primitive). Style Dictionary is the source of truth for
 * the primitive layer and the multi-platform exports.
 */

import StyleDictionary from "style-dictionary";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import fs from "node:fs";

const __dirname = dirname(fileURLToPath(import.meta.url));

const GENERATED_HEADER_CORE = `:root {
  /*
    UI3 core token import.
    Source library: UI3 Figma's UI Kit (Community), file 4kilp0ShQiYsoUPJdleqEH.
    Status: exact resolved values for the core app-consumed variables exported
    from Figma on 2026-06-16. Full 1015-variable raw archive is still broader
    than this app-facing core layer.

    Generated by Style Dictionary from tokens/primitive/*.json. Do not edit by hand.
  */
`;

/** Join the token path with "-" to form the CSS custom-property name. */
function cssVarName(token) {
  return `--${token.path.join("-")}`;
}

/** Pull the original (pre-resolved) reference string, e.g. "{figma.composa.color.bg}". */
function originalRef(token) {
  const orig = token.original?.$value ?? token.original?.value;
  return typeof orig === "string" ? orig : undefined;
}

/** Convert a "{a.b.c}" reference into a "--a-b-c" css var reference. */
function refToCssVar(ref) {
  const inner = ref.trim().replace(/^\{/, "").replace(/\}$/, "");
  return `var(--${inner.split(".").join("-")})`;
}

StyleDictionary.registerTransform({
  name: "name/composa-css",
  type: "name",
  transform: (token) => token.path.join("-"),
});

/**
 * CSS format for the PRIMITIVE layer. Emits a :root block with the base ($value)
 * and a [data-composa-mode="dark"] block from $extensions.composa.dark.
 */
StyleDictionary.registerFormat({
  name: "composa/primitive-css",
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens;
    const lightLines = tokens.map(
      (t) => `  ${cssVarName(t)}: ${t.$value ?? t.value};`
    );
    const darkLines = tokens
      .filter((t) => t.original?.$extensions?.composa?.dark !== undefined)
      .map(
        (t) =>
          `  ${cssVarName(t)}: ${t.original.$extensions.composa.dark};`
      );
    return (
      GENERATED_HEADER_CORE +
      "\n" +
      lightLines.join("\n") +
      "\n}\n\n" +
      `[data-composa-mode="dark"] {\n` +
      darkLines.join("\n") +
      "\n}\n"
    );
  },
});

/**
 * CSS format for the SEMANTIC layer. Emits --composa-* custom properties whose
 * values are var(--figma-composa-*) references (outputReferences-style), matching
 * the hand-authored aliases in design/tokens.css.
 */
StyleDictionary.registerFormat({
  name: "composa/semantic-css",
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((t) => {
      const ref = originalRef(t);
      const rhs = ref ? refToCssVar(ref) : t.$value ?? t.value;
      return `  ${cssVarName(t)}: ${rhs};`;
    });
    return (
      `/* Generated by Style Dictionary from tokens/semantic/*.json. Do not edit by hand. */\n` +
      `:root,\n[data-composa-mode] {\n` +
      lines.join("\n") +
      "\n}\n"
    );
  },
});

/** Build the aliases mirror map: "color.bg" -> "var(--figma-composa-color-bg)". */
StyleDictionary.registerFormat({
  name: "composa/core-json",
  format: ({ dictionary }) => {
    const aliases = {};
    for (const t of dictionary.allTokens) {
      const ref = originalRef(t);
      if (!ref) continue;
      // Canonical dotted alias key is carried on the token so the published
      // mirror keeps its original spelling (e.g. color.bg.secondaryOnCanvas).
      const ext = t.original?.$extensions?.composa ?? {};
      const key = ext.aliasKey ?? t.path.slice(1).join(".");
      aliases[key] = refToCssVar(ref);
      // Some semantic tokens publish an extra alias (e.g. the canonical brand color).
      if (ext.aliasKeyAlso) {
        for (const [alsoKey, alsoRef] of Object.entries(ext.aliasKeyAlso)) {
          aliases[alsoKey] = refToCssVar(alsoRef);
        }
      }
    }
    const meta = {
      source: {
        library: "UI3: Figma's UI Kit (Community)",
        fileKey: "4kilp0ShQiYsoUPJdleqEH",
        inventory: { colors: 946, sizing: 12, typography: 57, total: 1015 },
        status:
          "exact resolved values for app-consumed core variables exported from Figma on 2026-06-16; full 1015-variable raw archive remains out of scope for this core alias file",
        resolvedModes: ["Light", "Dark", "Slides-Light", "Slides-Dark"],
        generatedBy: "Style Dictionary (tokens/primitive + tokens/semantic)",
      },
      aliases,
    };
    return JSON.stringify(meta, null, 2) + "\n";
  },
});

/** Nested ES-module token object for web JS consumption. */
StyleDictionary.registerFormat({
  name: "composa/js-esm",
  format: ({ dictionary }) => {
    const tree = {};
    for (const t of dictionary.allTokens) {
      let node = tree;
      const segs = t.path;
      segs.forEach((seg, i) => {
        if (i === segs.length - 1) {
          node[seg] = t.$value ?? t.value;
        } else {
          node[seg] = node[seg] || {};
          node = node[seg];
        }
      });
    }
    return (
      `// Generated by Style Dictionary. Do not edit by hand.\n` +
      `// Nested Composa token object (resolved light-mode values) for web JS consumption.\n` +
      `export const tokens = ${JSON.stringify(tree, null, 2)};\n\n` +
      `export default tokens;\n`
    );
  },
});

/** Swift enum/struct stub for the color + sizing tokens (multi-platform showcase). */
StyleDictionary.registerFormat({
  name: "composa/swift",
  format: ({ dictionary }) => {
    const toCamel = (segs) =>
      segs
        .map((s, i) =>
          i === 0
            ? s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
            : s.charAt(0).toUpperCase() +
              s.slice(1).replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())
        )
        .join("");
    const colors = dictionary.allTokens.filter(
      (t) => t.path.includes("color")
    );
    const sizing = dictionary.allTokens.filter((t) =>
      ["radius", "space", "height"].some((k) => t.path.includes(k))
    );
    const colorCases = colors
      .map((t) => `    /// ${t.path.join(".")}\n    public static let ${toCamel(t.path.slice(1))} = "${t.$value ?? t.value}"`)
      .join("\n");
    const sizingCases = sizing
      .map((t) => `    /// ${t.path.join(".")}\n    public static let ${toCamel(t.path.slice(1))} = "${t.$value ?? t.value}"`)
      .join("\n");
    return (
      `// Generated by Style Dictionary. Do not edit by hand.\n` +
      `// Multi-platform showcase artifact — demonstrates that the same JSON source\n` +
      `// reaches Swift. Not wired into an Xcode target.\n\n` +
      `import Foundation\n\n` +
      `public enum ComposaTokens {\n` +
      `  public enum Color {\n${colorCases}\n  }\n\n` +
      `  public enum Sizing {\n${sizingCases}\n  }\n` +
      `}\n`
    );
  },
});

const cssTransforms = ["name/composa-css"];

const config = {
  log: { verbosity: "default" },
  platforms: {
    primitiveCss: {
      transforms: cssTransforms,
      buildPath: "design/generated/",
      source: ["tokens/primitive/**/*.json"],
      files: [
        {
          destination: "composa-core-tokens.css",
          format: "composa/primitive-css",
        },
      ],
    },
    semanticCss: {
      transforms: cssTransforms,
      buildPath: "design/generated/",
      files: [
        {
          destination: "composa-semantic-tokens.css",
          format: "composa/semantic-css",
          filter: (t) => t.path[0] === "composa",
        },
      ],
    },
    coreJson: {
      transforms: cssTransforms,
      buildPath: "design/generated/",
      files: [
        {
          destination: "composa-core-tokens.json",
          format: "composa/core-json",
          filter: (t) => t.path[0] === "composa",
        },
      ],
    },
    js: {
      transforms: cssTransforms,
      buildPath: "design/generated/",
      files: [
        {
          destination: "tokens.js",
          format: "composa/js-esm",
        },
      ],
    },
    swift: {
      transforms: cssTransforms,
      buildPath: "design/generated/",
      files: [
        {
          destination: "Tokens.swift",
          format: "composa/swift",
          filter: (t) => t.path[0] === "figma",
        },
      ],
    },
  },
};

/**
 * The primitive platform reads only the primitive source so dark $extensions are
 * available; the semantic/js/swift platforms read primitive + semantic so that
 * {figma.composa.*} references resolve.
 */
async function run() {
  // Pass 1: primitives only (keeps $extensions, no unresolved references).
  const sdPrimitive = new StyleDictionary({
    source: ["tokens/primitive/**/*.json"],
    platforms: { primitiveCss: config.platforms.primitiveCss },
  });
  await sdPrimitive.buildAllPlatforms();

  // Pass 2: primitive + semantic together so references resolve.
  const sdAll = new StyleDictionary({
    source: ["tokens/primitive/**/*.json", "tokens/semantic/**/*.json"],
    platforms: {
      semanticCss: config.platforms.semanticCss,
      coreJson: config.platforms.coreJson,
      js: config.platforms.js,
      swift: config.platforms.swift,
    },
  });
  await sdAll.buildAllPlatforms();
}

run().then(
  () => {
    // eslint-disable-next-line no-console
    console.log("build:tokens — Style Dictionary build complete.");
  },
  (err) => {
    // eslint-disable-next-line no-console
    console.error(err);
    process.exit(1);
  }
);

export default config;
