// Public entry for @composa-ui/react. License-clean: it bundles NO proprietary icon
// set. Components resolve the built-in structural glyphs (chevrons, check, close,
// etc. from builtin-glyphs.js) for their own anatomy, and accept content icons as
// slots -- pass a React node or component, or a string name resolved by an icon
// renderer you inject via createComposaComponents(React, { Icon }). The UI3-derived
// asset set used by Storybook and the demo app lives in ./story-runtime.js and is
// excluded from the published package.
import React from "react";
import { createPortal } from "react-dom";
import { createComposaComponents } from "./factory.js";

const components = createComposaComponents(React, { createPortal });

export const {
  Button,
  IconButton,
  ToggleButton,
  SplitButton,
  InputField,
  NumericInput,
  NumericInputMulti,
  ChipVariable,
  Chit,
  ColorInput,
  ComboInput,
  ComboInputDropdown,
  ChitInput,
  Slider,
  Switch,
  Radio,
  Checkbox,
  Tooltip,
  OverlayLayer,
  OverlayHost,
  OverlayPortal,
  Dialog,
  Dropdown,
  Menu,
  MenuRow,
  MenuDivider,
  MenuFooter,
  MenuMultiSelect,
  VerticalCell,
  ComposaAppIcon,
  NavigationRailItem,
  AppNavigationRail,
  NavigatorHeader,
  CollapseHeader,
  SlideThumb,
  SlideList,
  EditorNavigator,
  SlidesNavigator,
  TextPair,
  Label,
  Tree,
  TreeRow,
  ListCell,
  DialogRow,
  DialogHeaderCell,
  DialogHeader,
  DialogBody,
  DialogFooter,
  MenuHeadingCell,
  HeaderActions,
  Header,
  SegmentedControl,
  ControlGroup,
  AlignmentPicker,
  Tab,
  Tabs,
  Avatar,
  MultiplayerControl,
  CommentComposer,
  CommentItem,
  CommentThreadWindow,
  Badge,
  BadgeAnchor,
  NotificationBell,
  Notification,
  VisualBell,
  InspectorHeader,
  LayerHeader,
  PositionSection,
  LayoutSection,
  FillSection,
  StrokeSection,
  StrokeControlsSection,
  EffectsSection,
  ColorPickerDialog,
  ColorPickerTrigger,
  TypographyDialog,
  TypeStyleMenu,
  TypeStyleRow,
  FontsPickerMenu,
  LayoutGuideSettingsDialog,
  SelectionColorsSection,
  LayoutGuideSection,
  ExportSection,
  AppearanceSection,
  EditingInspector,
  EditorToolbar,
  EditorShell,
  SlidesEditorTemplate,
  CanvasSelectionOverlay,
} = components;

export { createComposaComponents };

export default components;
