// AUTO-GENERATED by tools/build-react18-types.mjs — DO NOT EDIT BY HAND.
//
// React-18-compatible types entry. Re-exports every type from the canonical
// "./index.js" declarations, then re-types each component as React.FunctionComponent
// so @types/react@18 accepts them directly in JSX (no `asFC()` cast needed).
//
// Consumers on React 18 can target this file, e.g. via a tsconfig paths entry
// or the package's "./react18" types export.

import type * as React from "react";

// Re-export all interfaces, type aliases, and non-component values (e.g.
// createComposaComponents, the default `components` object) unchanged.
export * from "./index.js";

import type {
  AlignmentPickerProps,
  AppNavigationRailProps,
  AppearanceSectionProps,
  AvatarProps,
  BadgeAnchorProps,
  BadgeProps,
  ButtonProps,
  CanvasSelectionOverlayProps,
  CheckboxProps,
  ChipVariableProps,
  ChitInputProps,
  ChitProps,
  CollapseHeaderProps,
  ColorInputProps,
  ColorPickerDialogProps,
  ColorPickerTriggerProps,
  ComboInputDropdownProps,
  ComboInputProps,
  CommentComposerProps,
  CommentItemProps,
  CommentThreadWindowProps,
  ComposaAppIconProps,
  ControlGroupProps,
  DialogBodyProps,
  DialogFooterProps,
  DialogHeaderCellProps,
  DialogHeaderProps,
  DialogProps,
  DialogRowProps,
  DropdownProps,
  EditingInspectorProps,
  EditorNavigatorProps,
  EditorShellProps,
  EditorToolbarProps,
  EffectsSectionProps,
  ExportSectionProps,
  FillSectionProps,
  FontsPickerMenuProps,
  HeaderActionsProps,
  HeaderProps,
  IconButtonProps,
  InputFieldProps,
  InspectorHeaderProps,
  LabelProps,
  LayerHeaderProps,
  LayoutGuideSectionProps,
  LayoutGuideSettingsDialogProps,
  LayoutSectionProps,
  ListCellProps,
  MenuDividerProps,
  MenuFooterProps,
  MenuHeadingCellProps,
  MenuMultiSelectProps,
  MenuProps,
  MenuRowProps,
  MultiplayerControlProps,
  NavigationRailItemProps,
  NavigatorHeaderProps,
  NotificationBellProps,
  NotificationProps,
  NumericInputMultiProps,
  NumericInputProps,
  OverlayHostProps,
  OverlayLayerProps,
  OverlayPortalProps,
  PositionSectionProps,
  RadioProps,
  SegmentedControlProps,
  SelectionColorsSectionProps,
  SlideListProps,
  SlideThumbProps,
  SliderProps,
  SlidesEditorTemplateProps,
  SlidesNavigatorProps,
  SplitButtonProps,
  StrokeControlsSectionProps,
  StrokeSectionProps,
  SwitchProps,
  TabProps,
  TabsProps,
  TextPairProps,
  ToggleButtonProps,
  TooltipProps,
  TreeProps,
  TreeRowProps,
  TypeStyleMenuProps,
  TypeStyleRowProps,
  TypographyDialogProps,
  VerticalCellProps,
  VisualBellProps,
} from "./index.js";

export declare const Button: React.FC<ButtonProps>;
export declare const IconButton: React.FC<IconButtonProps>;
export declare const ToggleButton: React.FC<ToggleButtonProps>;
export declare const SplitButton: React.FC<SplitButtonProps>;
export declare const InputField: React.FC<InputFieldProps>;
export declare const NumericInput: React.FC<NumericInputProps>;
export declare const NumericInputMulti: React.FC<NumericInputMultiProps>;
export declare const ChipVariable: React.FC<ChipVariableProps>;
export declare const Chit: React.FC<ChitProps>;
export declare const ColorInput: React.FC<ColorInputProps>;
export declare const ComboInput: React.FC<ComboInputProps>;
export declare const ComboInputDropdown: React.FC<ComboInputDropdownProps>;
export declare const ChitInput: React.FC<ChitInputProps>;
export declare const Switch: React.FC<SwitchProps>;
export declare const Slider: React.FC<SliderProps>;
export declare const Radio: React.FC<RadioProps>;
export declare const Checkbox: React.FC<CheckboxProps>;
export declare const Tooltip: React.FC<TooltipProps>;
export declare const OverlayLayer: React.FC<OverlayLayerProps>;
export declare const OverlayHost: React.FC<OverlayHostProps>;
export declare const OverlayPortal: React.FC<OverlayPortalProps>;
export declare const Dialog: React.FC<DialogProps>;
export declare const Dropdown: React.FC<DropdownProps>;
export declare const MenuRow: React.FC<MenuRowProps>;
export declare const MenuDivider: React.FC<MenuDividerProps>;
export declare const MenuFooter: React.FC<MenuFooterProps>;
export declare const Menu: React.FC<MenuProps>;
export declare const MenuMultiSelect: React.FC<MenuMultiSelectProps>;
export declare const TextPair: React.FC<TextPairProps>;
export declare const Label: React.FC<LabelProps>;
export declare const TreeRow: React.FC<TreeRowProps>;
export declare const Tree: React.FC<TreeProps>;
export declare const VerticalCell: React.FC<VerticalCellProps>;
export declare const ComposaAppIcon: React.FC<ComposaAppIconProps>;
export declare const NavigationRailItem: React.FC<NavigationRailItemProps>;
export declare const AppNavigationRail: React.FC<AppNavigationRailProps>;
export declare const NavigatorHeader: React.FC<NavigatorHeaderProps>;
export declare const CollapseHeader: React.FC<CollapseHeaderProps>;
export declare const SlideThumb: React.FC<SlideThumbProps>;
export declare const SlideList: React.FC<SlideListProps>;
export declare const EditorNavigator: React.FC<EditorNavigatorProps>;
export declare const SlidesNavigator: React.FC<SlidesNavigatorProps>;
export declare const ListCell: React.FC<ListCellProps>;
export declare const DialogRow: React.FC<DialogRowProps>;
export declare const DialogHeaderCell: React.FC<DialogHeaderCellProps>;
export declare const DialogHeader: React.FC<DialogHeaderProps>;
export declare const DialogBody: React.FC<DialogBodyProps>;
export declare const DialogFooter: React.FC<DialogFooterProps>;
export declare const MenuHeadingCell: React.FC<MenuHeadingCellProps>;
export declare const HeaderActions: React.FC<HeaderActionsProps>;
export declare const Header: React.FC<HeaderProps>;
export declare const SegmentedControl: React.FC<SegmentedControlProps>;
export declare const ControlGroup: React.FC<ControlGroupProps>;
export declare const AlignmentPicker: React.FC<AlignmentPickerProps>;
export declare const Tab: React.FC<TabProps>;
export declare const Tabs: React.FC<TabsProps>;
export declare const Avatar: React.FC<AvatarProps>;
export declare const MultiplayerControl: React.FC<MultiplayerControlProps>;
export declare const CommentComposer: React.FC<CommentComposerProps>;
export declare const CommentItem: React.FC<CommentItemProps>;
export declare const CommentThreadWindow: React.FC<CommentThreadWindowProps>;
export declare const Badge: React.FC<BadgeProps>;
export declare const BadgeAnchor: React.FC<BadgeAnchorProps>;
export declare const NotificationBell: React.FC<NotificationBellProps>;
export declare const Notification: React.FC<NotificationProps>;
export declare const VisualBell: React.FC<VisualBellProps>;
export declare const InspectorHeader: React.FC<InspectorHeaderProps>;
export declare const LayerHeader: React.FC<LayerHeaderProps>;
export declare const PositionSection: React.FC<PositionSectionProps>;
export declare const LayoutSection: React.FC<LayoutSectionProps>;
export declare const FillSection: React.FC<FillSectionProps>;
export declare const StrokeSection: React.FC<StrokeSectionProps>;
export declare const StrokeControlsSection: React.FC<StrokeControlsSectionProps>;
export declare const EffectsSection: React.FC<EffectsSectionProps>;
export declare const ColorPickerDialog: React.FC<ColorPickerDialogProps>;
export declare const ColorPickerTrigger: React.FC<ColorPickerTriggerProps>;
export declare const TypographyDialog: React.FC<TypographyDialogProps>;
export declare const TypeStyleMenu: React.FC<TypeStyleMenuProps>;
export declare const TypeStyleRow: React.FC<TypeStyleRowProps>;
export declare const FontsPickerMenu: React.FC<FontsPickerMenuProps>;
export declare const LayoutGuideSettingsDialog: React.FC<LayoutGuideSettingsDialogProps>;
export declare const SelectionColorsSection: React.FC<SelectionColorsSectionProps>;
export declare const LayoutGuideSection: React.FC<LayoutGuideSectionProps>;
export declare const ExportSection: React.FC<ExportSectionProps>;
export declare const AppearanceSection: React.FC<AppearanceSectionProps>;
export declare const EditingInspector: React.FC<EditingInspectorProps>;
export declare const EditorToolbar: React.FC<EditorToolbarProps>;
export declare const EditorShell: React.FC<EditorShellProps>;
export declare const SlidesEditorTemplate: React.FC<SlidesEditorTemplateProps>;
export declare const CanvasSelectionOverlay: React.FC<CanvasSelectionOverlayProps>;
