// Story + internal-app runtime. This wires the components with the UI3-derived
// `iconAssets` so Storybook and the Figma-Video app can render string-named
// content icons (icon="move", etc.). It is NOT part of the published package —
// the proprietary assets must not ship. The public entry is ./index.js, which
// wires no icon set (content icons are passed in as slots; structural glyphs are
// the built-in license-clean set).
import React from "react";
import { createPortal } from "react-dom";
import { createComposaComponents } from "./factory.js";
import { ComposaIcon, iconAssets } from "./story-icons.js";

const components = createComposaComponents(React, { Icon: ComposaIcon, createPortal });

export const {
  Button,
  IconButton,
  ToggleButton,
  SplitButton,
  InputField,
  NumericInput,
  NumericInputMulti,
  ChipVariable,
  Chit,
  ColorInput,
  ComboInput,
  ComboInputDropdown,
  ChitInput,
  Switch,
  Radio,
  Checkbox,
  Tooltip,
  OverlayLayer,
  OverlayHost,
  OverlayPortal,
  Dialog,
  Dropdown,
  Menu,
  MenuRow,
  MenuMultiSelect,
  VerticalCell,
  ComposaAppIcon,
  NavigationRailItem,
  AppNavigationRail,
  NavigatorHeader,
  CollapseHeader,
  SlideThumb,
  SlideList,
  EditorNavigator,
  SlidesNavigator,
  TextPair,
  Label,
  Tree,
  TreeRow,
  ListCell,
  DialogRow,
  DialogHeaderCell,
  DialogHeader,
  DialogBody,
  DialogFooter,
  MenuHeadingCell,
  HeaderActions,
  Header,
  SegmentedControl,
  ControlGroup,
  AlignmentPicker,
  Tab,
  Tabs,
  Avatar,
  MultiplayerControl,
  CommentComposer,
  CommentItem,
  CommentThreadWindow,
  Badge,
  BadgeAnchor,
  NotificationBell,
  Notification,
  VisualBell,
  InspectorHeader,
  LayerHeader,
  PositionSection,
  LayoutSection,
  FillSection,
  StrokeSection,
  StrokeControlsSection,
  EffectsSection,
  ColorPickerDialog,
  ColorPickerTrigger,
  TypographyDialog,
  TypeStyleMenu,
  TypeStyleRow,
  FontsPickerMenu,
  LayoutGuideSettingsDialog,
  SelectionColorsSection,
  LayoutGuideSection,
  ExportSection,
  AppearanceSection,
  EditingInspector,
  EditorToolbar,
  EditorShell,
  SlidesEditorTemplate,
  CanvasSelectionOverlay,
} = components;

export { ComposaIcon, iconAssets, createComposaComponents };

export default components;
