// Generate skills/composa-ui/CATALOG.md from design/component-api.json.
//
// The public composa-ui skill bundles a component catalog so third parties get
// real props/variants without the repo or a localhost MCP. That catalog is
// DERIVED data — if hand-maintained it drifts from the API. So it is generated
// here from component-api.json (which is itself gated against the factory by
// verify-design-system-contracts.js). Run with --check to fail when out of sync.
//
//   node tools/build-catalog.mjs            # write CATALOG.md
//   node tools/build-catalog.mjs --check    # exit 1 if CATALOG.md is stale

import fs from "node:fs";
import { fileURLToPath } from "node:url";

const apiUrl = new URL("../design/component-api.json", import.meta.url);
const outUrl = new URL("../skills/composa-ui/CATALOG.md", import.meta.url);
const api = JSON.parse(fs.readFileSync(apiUrl, "utf8"));

const fmtVal = (v) => (Array.isArray(v) ? v.join(" · ") : String(v));

const propsBlock = (props = {}) =>
  Object.entries(props)
    .map(([k, v]) => `- \`${k}\`: ${fmtVal(v)}`)
    .join("\n");

const families = Object.entries(api.componentFamilies || {})
  .map(([name, d]) => {
    const figma = (d.figma || []).join(" · ");
    const head = `### ${name} — ${d.variantCount ?? "?"} variants`;
    const meta = `_Figma: ${figma} · source: ${d.source}_`;
    return `${head}\n${meta}\n\n${propsBlock(d.props)}`;
  })
  .join("\n\n");

const support = Object.keys(api.supportComponents || {}).join(" · ");
const renderer = api.renderer?.current ?? "react-app";

const out = `<!-- GENERATED by tools/build-catalog.mjs from design/component-api.json. DO NOT EDIT.
     Run \`npm run build:catalog\` to regenerate; \`npm run check\` fails if it drifts. -->

# Composa UI — component catalog

The components exposed by \`@composa-ui/react\` (schema ${api.schemaVersion ?? "?"}, renderer
\`${renderer}\`). Use the exact prop values listed here — do not invent props or
variants. Each family is sourced from Figma UI3 and implemented in \`src/react/factory.js\`.

For usage, anatomy, and accessibility (the prose this catalog deliberately does NOT
duplicate), see the Storybook: https://composa-ui.github.io/react — or, if running it
locally, the Storybook MCP at \`http://localhost:6011/mcp\`
(\`list-all-documentation\` → \`get-documentation\`), which is always in sync.

## Component families

${families}

## Support components & primitives

${support}

> Overlays (\`OverlayHost\`, \`OverlayPortal\`, \`OverlayLayer\`) are required infrastructure:
> every tooltip, menu, and dialog portals into the nearest \`OverlayHost\`. See SKILL.md.
`;

const checkMode = process.argv.includes("--check");
const path = fileURLToPath(outUrl);

if (checkMode) {
  const current = fs.existsSync(outUrl) ? fs.readFileSync(outUrl, "utf8") : "";
  if (current !== out) {
    console.error(
      "CATALOG.md is out of sync with component-api.json. Run `npm run build:catalog`."
    );
    process.exit(1);
  }
  console.log("build-catalog --check — CATALOG.md is in sync.");
} else {
  fs.writeFileSync(outUrl, out);
  console.log(`Wrote ${path} (${Object.keys(api.componentFamilies || {}).length} families).`);
}
